---
title: "R Notebook"
output: html_notebook
---

```{r}
library(jsonlite)
library(tidyverse)
library(tidyr)
library(dplyr)
library(lubridate)

watch_history <- jsonlite::read_json("data/watch-history.json",simplifyVector = T)
# search_history <- jsonlite::read_json("data/search-history.json")

data <- watch_history %>%
  
  #clean colnames
  janitor::clean_names() %>% 
  
  #unnest nested cols
  unnest(cols = c(subtitles,products,activity_controls,description,details),names_sep="_") %>% 
  
  #remove non-relevant data (YouTube TV, YouTube Music, etc.)
  filter(is.na(details_name),
         header == "YouTube",
         !is.na(subtitles_name)) %>% 

  #transform cols
  mutate(
         title = str_remove(title,"^Watched "),
         time = lubridate::as_datetime(time)
  ) %>% 
  
  #select relevant cols
  select(video_title = title,
         video_url = title_url,
         channel_name = subtitles_name,
         channel_url = subtitles_url,
         timestamp = time)

data_pulling_timestamp <- c(data %>% 
  filter(channel_name %in% c("TMG Studios"),
         timestamp >= lubridate::as_date("2020-12-19"),
         timestamp <= lubridate::as_date("2020-12-21")) %>% 
  select(timestamp) %>% pull(),

data %>% 
  filter(channel_name %in% c("TMG Studios"),
         timestamp >= lubridate::as_date("2020-12-21"),
         timestamp <= lubridate::as_date("2020-12-25")) %>% 
  select(timestamp) %>% pull(),

data %>% 
  filter(channel_name %in% c("TMG Studios"),
         timestamp >= lubridate::as_date("2021-12-09"),
         timestamp <= lubridate::as_date("2021-12-10")) %>% 
  select(timestamp) %>% pull(),

data %>% 
  filter(channel_name %in% c("TMG Studios","Trillionaire Mindset"),
         timestamp > lubridate::as_date("2022-08-16"),
         timestamp < lubridate::as_date("2022-08-17")) %>% 
  select(timestamp) %>% pull()
)

data <- data %>% 
  filter(!(timestamp %in% data_pulling_timestamp),
         channel_name != "Ben Kates")

data %>% 
  saveRDS(file="saved_watch_history.RDS")
```

```{r}

data <- readRDS(file="saved_watch_history.RDS")

data %>% 
  count(channel_name,sort = T) %>% 
  mutate(rolling_sum = rol)

data %>% 
  filter(channel_name == "TMG Studios") %>% 
  mutate(week = lubridate::floor_date(timestamp,unit = "week")) %>% 
  count(week) %>% 
  
  ggplot(aes(x = week,day,y = n)) +
  geom_col()

```









